questions
MaKu-kodilla/ReactJS_practice pull request #3
Opened 2018-05-01 21:21 UTC by MaKu-kodilla

nie mogę wpisywać żadnych danych w poszczególne inputy.

Wiesz może gdzie może być przyczyna? :)

2018-05-04 12:30 UTC, michal-bootcamp requested changes
tak, jak rozmawialismy, danych nie mozna wpisywac, bo inputy sa pod wladza reacta i trzeba by je obsluzyc po stronie reacta :)

ostyluj prosze appke inspirujac sie mockupem pokazanym na poczatku submodulu (Ustalenie struktury aplikacji)

2018-05-04 12:30 UTC, michal-bootcamp commented on Zadanie 14.3 Aplikacja z listą kontaktów/components/Contact.js
> +                    src: 'http://icons.veryicon.com/ico/System/100%20Flat%20Vol.%202/contacts.ico'
zamiast zaciagac obrazek z innej lokalizacji, dodaj go do projektu i podaj sciezke wzgledna

2018-05-05 16:15 UTC, MaKu-kodilla commented on Zadanie 14.3 Aplikacja z listą kontaktów/components/Contact.js
> +                    src: 'http://icons.veryicon.com/ico/System/100%20Flat%20Vol.%202/contacts.ico'
może tak być, czy coś pozmieniać? :)

2018-05-05 23:21 UTC, michal-bootcamp commented on Zadanie 14.3 Aplikacja z listą kontaktów/components/Contact.js
> +                    src: 'http://icons.veryicon.com/ico/System/100%20Flat%20Vol.%202/contacts.ico'
ostylowanie jest git, tylko jeszcze ten obrazek ikony - nie zaciagaj go z veryicon.com, tylko lokalnie np z `img/contacts.ico`

2018-05-09 07:58 UTC, merged